version: '3.8'

services:  
  web:
    build: .    
    command: python app.py
    volumes:     
      - .:/code
    ports:      
      - "5000:5000"
    environment:      
      FLASK_ENV: development